// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example of what your app's Firebase configuration should be.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjc81TdpTWm28yRA77rIlR1OcoQZxyip4',
    appId: '1:273572564767:web:your-web-app-id',
    messagingSenderId: '273572564767',
    projectId: 'xtrchat-a1def',
    authDomain: 'xtrchat-a1def.firebaseapp.com',
    storageBucket: 'xtrchat-a1def.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDudVqJrOmqbYLuTEySQzLK6l0BIG2o3IQ',
    appId: '1:273572564767:android:3375cfd6b1ef2f3aec2a2a',
    messagingSenderId: '273572564767',
    projectId: 'xtrchat-a1def',
    storageBucket: 'xtrchat-a1def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjc81TdpTWm28yRA77rIlR1OcoQZxyip4',
    appId: '1:273572564767:ios:02489909a2b1e138ec2a2a',
    messagingSenderId: '273572564767',
    projectId: 'xtrchat-a1def',
    storageBucket: 'xtrchat-a1def.firebasestorage.app',
    iosBundleId: 'com.xtrchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjc81TdpTWm28yRA77rIlR1OcoQZxyip4',
    appId: '1:273572564767:ios:02489909a2b1e138ec2a2a',
    messagingSenderId: '273572564767',
    projectId: 'xtrchat-a1def',
    storageBucket: 'xtrchat-a1def.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
